# Generated by Django 5.0 on 2025-04-03 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_participant_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='event',
            name='edit_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='PersonalizedInvitation',
            fields=[
                ('invitation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.invitation')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('events.invitation',),
        ),
    ]
