# Generated by Django 5.0 on 2025-03-31 13:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_participant_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='participant',
            name='password',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
