# Generated by Django 5.0 on 2025-04-03 19:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_comment_uuid_delete_personalizedinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedInvitation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_invitations', to='events.event')),
            ],
        ),
    ]
