'use client';

import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { useRouter } from 'next/navigation';


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
    const router = useRouter();
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="layout-container">
            <aside className="sidebar">
                <Link href="/" className="logo-link" onClick={() => {router.push('/');}}>
                    <img src="/logo.png" alt="Logo" className="logo" />
                </Link>
                <button className="create-event-button" onClick={() => {router.push('/create-event');}}>
                    Create Event
                </button>
            </aside>

            <main className="main-content">
                {children}
            </main>

            <aside className="sidebar"></aside>
        </div>
        </body>
        </html>
    );
}